name: docker build and push

on:
  workflow_run:
    workflows: ["ci pipeline"]
    types:
      - completed
      
  workflow_dispatch:

env:
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  ECR_REPO_NAME: ${{ vars.AWS_REPO }}
  ECR_REGISTRY: ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com
  IMAGE_TAG: ${{ github.sha }}

permissions:
  contents: write
  id-token: write

jobs:

  docker-build-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: docker-build-push
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/docker-build-push-role-2
          aws-region: ${{ env.AWS_REGION }}

      - name: login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
            registry-type: private
            mask-password: true   

      - name: Build Docker image
        run: docker build -t ${{ env.ECR_REPO_NAME }}:${{ env.IMAGE_TAG }} ./app/gatus

      - name: tag Docker image for ECR
        run: docker tag ${{ env.ECR_REPO_NAME }}:${{ env.IMAGE_TAG }} ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPO_NAME }}:${{ env.IMAGE_TAG }}

      - name: push Docker image
        run: docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPO_NAME }}:${{ env.IMAGE_TAG }}

      - name: write current image tag to file
        run: printf "%s" "${{ env.IMAGE_TAG }}" > image_tag.txt

      - name: commit image tag
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add image_tag.txt
          git commit -m "Update image tag to ${{ env.IMAGE_TAG }}"
          git push origin ${{ github.ref }}

      - name: Docker build and push summary
        run: |
          echo "### Docker image successfully built and pushed" >> $GITHUB_STEP_SUMMARY

      - name: update CURRENT_IMAGE_TAG variable in repo variables
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          event-type: update-image-tag
          client-payload: '{"CURRENT_IMAGE_TAG":"${{ env.IMAGE_TAG }}"}'
